gomb1.addEventListener("click", function(){
    bek1.textContent = `A Massospondylus (ógörög eredetű nevének jelentése 'megnyúlt gerinc') a prosauropoda dinoszauruszok egyik neme, amely a kora jura kor hettangi – pliensbachi korszakában, mintegy 200–183 millió évvel ezelőtt élt. Ez az egyik legelsőként elnevezett dinoszaurusz, a holotípusát Richard Owen írta le 1854-ben, egy Dél-Afrikában talált lelet alapján. Azóta Dél-Afrika más részein, Lesothóban és Zimbabwében is megtalálták a fosszíliáit. Az Arizona állambeli Kayenta-formációból, Indiából és Argentínából is kerültek elő olyan maradványok, amelyeket a Massospondylushoz kapcsoltak, de elképzelhető, hogy ezek a leletek nem ehhez a nemhez tartoznak.Típusfaja a M. carinatus, de a felfedezése utáni 150 évben további hét fajt is elneveztek, melyek közül jelenleg csak a M. kalae számít érvényesnek. Ezen időszak utolsó éveiben a prosauropodák rendszertana sokat változott, és számos tudós vitatni kezdte, hogy a Massospondylust a dinoszauruszok evolúciós fájának megfelelő pontján helyezték-e el. A nem számára megalkotott családnév, a Massospondylidae érvényessége a prosauropodák kapcsolatainak változásai miatt szintén vitatottá vált. Nem világos az sem, hogy mely más dinoszauruszokkal tartozott egy csoportba (amennyiben voltak ilyenek); de a családot több 2007-ben megjelent cikk is érvényesnek tekinti.Valószínűleg növényevő volt, bár létezik olyan elképzelés, ami szerint prosauropodák mindenevők voltak. Karcsú testtel, hosszú nyakkal és farokkal rendelkezett, mellső lábainak hüvelykujjain éles karmok helyezkedtek el, melyeket a táplálkozás vagy esetleg a védekezés során használhatott. Néhány újabb vizsgálat szerint a Massospondylus folyamatosan növekedett egész életében, testében a madarakéhoz hasonló légzsákok voltak, és feltehetően gondozta az utódait.`
})

gomb2.addEventListener("click", function(){
    bek1.textContent = `A Massospondylus közepes méretű prosauropoda volt, testhossza körülbelül 4–[1][2][3] 6[4][5] méter, tömege mintegy 135[3]-250[6] kilogramm lehetett. Habár sokáig négy lábon járó állatként ábrázolták, egy 2007-ben, a mellső lábakon elvégzett anatómiai vizsgálat megállapította, hogy a két végtag mozgásának korlátozottsága megnehezíthette ezt a járásmódot. Emellett a vizsgálat kizárta az ujjízületeken való járás valószínűségét és a helyváltoztatás más módjait is, arra hivatkozva, hogy a Massospondylus csak korlátozott mértéken volt képes megcsavarni a mellső végtagjait. Ezért, még ha a tömege alapján négy lábon járónak tűnik is, kénytelen volt a hátsó lábain mozogni.[7]Egy Massospondylus csontváza a londoni Natural History Museumban, a 2007 előtt feltételezett testtartásbanA Massospondylus ennek ellenére a legtöbb szempontból átlagos prosauropoda volt. Karcsú testtel, kis fejjel, hosszú nyakkal és farokkal rendelkezett. Nyakát 9, hátát 13, keresztcsontját 3, farkát pedig 40 csigolya alkotta. Szeméremcsontja – a hüllőmedencéjűekre jellemző módon – előre irányult. Könnyebb testfelépítésű volt, mint a hozzá hasonló Plateosaurus.[8] Egy újabb felfedezés alapján a Massospondylus jól fejlett kulcscsontokkal rendelkezett, melyek a villacsonthoz hasonlóan összekapcsolódva helyezkedtek el, így valószínűleg nem volt képes mozgatni a vállait, de maguk a kulcscsontok mégsem voltak olyan fejletlenek és használhatatlanok, mint azoknál a dinoszauruszoknál, amelyeknek nincs igazi villacsontjuk. Ez a felfedezés azt is jelzi, hogy a madarak villacsontja a kulcscsontokból alakult ki.[9]A Plateosaurushoz hasonlóan minden lábán öt ujja volt, a hüvelykujjain pedig nagy karmokat viselt, amiket feltehetően táplálkozásra vagy a ragadozókkal szembeni védekezésre használt. A mellső láb negyedik és ötödik ujja kisebb volt, aszimmetrikus látszatot keltett. A 2007-es vizsgálat megállapította, hogy a kéztartás félig szupinált („imádkozó tartás”) volt, a tenyerek egymás felé fordultak; a csuklókat sosem találták meg elfordított helyzetben a még ízelt (kapcsolódó részekből álló) fosszíliáknál.[7]`
})
gomb3.addEventListener("click", function(){
    bek1.textContent = `Fejének hossza körülbelül a combcsont hosszának felét érte el. Számos nyílás található rajta, melyek csökkentik a tömegét és izomtapadási pontokat, illetőleg helyet biztosítanak az érzékszervek számára. A nyílások a koponya két oldalán szimmetrikusan helyezkednek el. Elöl két nagyobb méretű, ellipszis alakú orrnyílás található. A szemnyílások aránylag nagyobbak, mint a hasonló nemeknél, például a Plateosaurusnál. A szemek és az orr között elhelyezkedő oldalsó nyílás (fenestra antorbitalis) kisebb, mint a Plateosaurusé. A koponya hátsó részén, közvetlenül a szemek mögött oldalt és felül, valamint az állkapocs oldalán, további nyílások találhatók.[8] A koponya szélesebb és rövidebb, mint a Plateosaurusé, de az összehasonlítást megnehezíti, hogy az egyes példányok koponyái sérültek, csak a helyreállított változataik vizsgálhatók.[8] A különböző egyedek koponyái eltérő jellegzetességeket mutatnak; például más a szemnyílás felső szegélyének vastagsága és a felső állcsont alsó részének magassága. Ezek a különbségek talán a nemi kétalakúság jelei,[10] vagy az egyedek közti kisebb eltérések lehetnek.[11]Más prosauropodákhoz hasonlóan valószínűleg a Massospondylusnak is volt a táplálék kihullását gátló pofarésze, mivel az állkapocs csontok felszínén a hüllőkre jellemző apró lyukaknál jóval nagyobbak találhatók a véredények számára.[8] A. W. Crompton és John Attridge 1986-ban készült tanulmányukban megállapították, hogy a Massospondylus koponyák a túlharapás jeleit mutatják, és azt feltételezték, hogy az alsó állkapocs elején egy elszarusodott csőrszerű képződmény helyezkedhetett el, ami az alsó és a felső fogsor közötti távolságot töltötte ki.[12] A feltételezésről azonban a későbbiekben megállapították, hogy helytelen, mivel az eltérést a fosszíliára alulról és felülről ható nyomás okozta. A hasonló módon nem sérült koponyáknál nem észlelhető a túlharapás.[10] Emellett úgy tűnik, hogy a fogak alaktanára vonatkozó megállapítások a fogak állkapocsban való elhelyezkedésén alapulnak.[13] Bár a Massospondylus heterodont fogazata nagyobb fogak közötti eltérést mutat, mint a Plateosaurusé, nem ér el olyan szintű specializációt, ami például a Heterodontosaurusnál tapasztalható.[13] A felső fogsor elülső fogai kör keresztmetszetűek és kúposak, ellentétben a hátsó fogakkal, melyek laposabbak és ovális keresztmetszetűek.[8][13]`
})
gomb4.addEventListener("click", function(){
    bek1.textContent = `A Massospondylus első fosszíliáit Richard Owen írta le 1854-ben.[14] Neve az ógörög masszon ('megnyúlt')[15] és szpondülosz ('gerinc') szavakból származik.[16] A fosszíliákat J. M. Orpen fedezte fel az Elliot-formáció felső részén, a dél-afrikai Harrismith közelében, 1853-ban. A maradványok között megtalálhatók voltak a nyak, a hát és a farok csigolyák, egy lapocka, egy felkarcsont, egy részleges csípő, egy combcsont, egy sípcsont és a kezek, valamint a lábak csontjai. A holotípus a londoni Royal College of Surgeons gyűjteményébe került, majd megsemmisült a második világháború alatt; csupán a másolatai maradtak fenn.[17] A későbbiekben feltételezett Massospondylus maradványok kerültek elő a dél-afrikai Elliot-formáció felső részéről, a clarens formációból, a bushveldi homokkő formáció dél-afrikai és lesothói részéről; a zimbabwei Forest Sandstone-formációból és a Karroo Sandstone-formáció felső részéről; valamint az arizonai Kayenta-formációból. Ezek a leletek legalább 80 hiányos csontvázat és négy koponyát tartalmaznak, egy részük fiatal, más részük pedig felnőtt egyedektől származik.[8]

Az arizonai lelet egy 1985-ös leírásból vált ismertté. Ez a példány 25%-kal nagyobb koponyával rendelkezett, mint a legnagyobb afrikai társa.[13] A felső állkapcsa elülső részén (premaxilla) 4, a hátsó részén (maxilla) pedig 16 fog található. A dinoszauruszok között egyedülálló módon apró, egy milliméter hosszú palatális fogakkal is rendelkezett.[18] Az afrikai koponyák újabb vizsgálata azonban feltárta, hogy a kayentai példány nem tartozik a Massospondylus nembe.[19]

Argentínából is ismert Massospondylusról szóló beszámoló,[8] de erről a leletről később megállapították, hogy egy közeli rokon nemhez tartozik. A több részleges csontvázat és legalább egy koponyát tartalmazó fosszíliákra a kora jura kori Cañon del Colorado-formációban találtak rá, az argentínai San Juan mellett. Az anyag 2009-ben az Adeopapposaurus nevet kapta.[20`
})
gomb5.addEventListener("click", function(){
    bek1.textContent = `Számos fajt neveztek el, azonban a legtöbbet már nem tekintik érvényesnek. A típusfaj a Richard Owen által elnevezett M. carinatus.[21] A további fajok közé tartozik a M. browni (Harry Seeley, 1895),[22] a M. harriesi (Robert Broom 1911),[23] a M. hislopi (Richard Lydekker, 1890),[24] a M. huenei (Cooper, 1981),[25] a M. kaalae (Barrett 2009),[26] a M. rawesi (Lydekker, 1890)[24] és a M. schwarzi (Haughton, 1924).[27]

Az M. browni, a M. harriesi és a M. schwarzi az Elliot-formáció felső részéről kerültek elő, a dél-afrikai Cape Province-ból. Mindhárom töredékes maradványok alapján ismert, és a legújabb vizsgálat alapján mindhárom kétséges névként (nomen dubium) kezelendő.[8] Az M. brownit két nyak-, két hát-, és három farokcsigolya, valamint a hátsó láb különböző részei alapján írták le.[22] Az M. harriesinek csupán egy mellső lábát találták meg.[23] Az M. schwarzinak mindössze az egyik hiányos lába és a keresztcsontja került elő.[27] Az M. hislopi és a M. rawesi Indiából származik.[24] Az M. hislopi gerincmaradványára az Andhra Pradeshnél levő Maleri-formáció késő triász kori rétegében bukkantak rá, míg a M. rawesinek csak egy foga került felszínre a maharashtrai Takli-formáció késő kréta kori rétegéből.[28] A legújabb vizsgálat a M. hislopit kísérletképpen meghatározatlan sauropodomorphaként sorolta be,[8] a M. rawesi azonban vagy egy theropoda maradványa,[29] vagy nem dinoszauruszhoz tartozik.[17] Michael R. Cooper szerint a M. huenei a Lufengosaurus huenei egyik változata lehet, és azt javasolta, hogy a Lufengosaurust tekintsék a Massospondylus szinonimájának,[25] a javaslatát azonban elutasították.[8]

A M. kaalae-ról 2009-ben készült leírás egy részleges koponya alapján, ami az Elliot-formáció felső részén került elő a dél-afrikai Herschel-körzetben. Ez a faj ugyanabból az időből és térségből származik, amelyből a M. carinatus. A típusfaja az agyüreg morfológiájában és a koponya más tulajdonságaiban, többek között a premaxilla arányaiban tér el.[26`
})
gomb6.addEventListener("click", function(){
    bek1.textContent = `Több dinoszaurusz nevet is a Massospondylus szinonimájaként kezelnek. Ezek közé tartozik az Aristosaurus, a Dromicosaurus, a Gryponyx, a Hortalotarsus, a Leptospondylus, és a Pachyspondylus, melyek kevés tudományos értékkel bíró bizonytalan elnevezések.[25] A Hortalotarsus skirtopodust Harry Seeley azonosította 1894-ben, néhány lábcsont alapján. A következő évben Richard Owen néhány csigolya fosszíliát megvizsgálva alkotta meg a Leptospondylus capensis és a Pachyspondylus orpenii nevet. Ezek a fosszília töredékek a második világháborúban megsemmisültek. Az Aristosaurus erectus nevet E. C. N. van Hoepen adta 1920-ban, egy olyan példánynak, melynek majdnem a teljes csontváza megőrződött. A szintén Hoepen által elnevezett Dromicosaurus gracilisnek csak a hiányos csontváza került elő. A mindössze egy csípő alapján ismert Gryponyx taylori fajt Sidney H. Haughton nevezte el 1924-ben. Ezek a fosszíliák Dél-Afrika hettangi vagy sinemuri korszakához tartozó rétegeiből kerültek elő, ahol a Massospondylust is megtalálták.[30][31] A zoológiai nevezéktan szabályai szerint ezek az elnevezések szinonimáknak tekintendők. Mivel a Massospondylus név korábban szerepelt tudományos cikkben, elsőbbséget élvez.`
})
gomb7.addEventListener("click", function(){
    bek1.textContent = `A Massospondylus a prosauropodákhoz, a korai hüllőmedencéjű dinoszauruszok egy csoportjához tartozik, amely a triász és a jura időszak idején élt, de a jura végére kihalt. Ebbe a csoportba tartozott például a Plateosaurus,[8] a Yunnanosaurus[8] és a Riojasaurus[33] is. A bazális sauropodomorphák rendszertana folyamatosan változik, és a filogenetikus rendszertanban számos, korábban klasszikus prosauropodának tekintett nemet eltávolítottak a csoportból, arra hivatkozva, hogy nem alkotnak kládot (olyan természetes csoportot, amely egy közös ős valamennyi leszármazottját tartalmazza). Tisztázatlan, hogy a prosauropodák közül mely állatok alkotnak monofiletikus (természetes) csoportot.

Adam M. Yates és James W. Kitching 2003-ban létrehozott egy kládot, ami tartalmazza a Riojasaurust, a Plateosaurust, a Coloradisaurust, a Massospondylust és a Lufengosaurust.[34]

Peter M. Galton és Paul Upchurch (2004-es) kládjában az Ammosaurus, az Anchisaurus, az Azendohsaurus, a Camelotia, a Coloradisaurus, az Euskelosaurus, a Jingshanosaurus, a Lessemsaurus, a Lufengosaurus, a Massospondylus, a Melanorosaurus, a Mussaurus, a Plateosaurus, a Riojasaurus, a Ruehleia, a Saturnalia, a Sellosaurus, a Thecodontosaurus, a Yimenosaurus és a Yunnanosaurus monofiletikus prosauropoda csoportot alkot.[8] Jeffrey A. Wilson (2005-ös) véleménye szerint a Massospondylus, a Jingshanosaurus, a Plateosaurus és a Lufengosaurus természetes csoportot alkot, a Blikanasaurusszal és az Antetonitrusszal, melyek feltételezett sauropodák.[35] Matthew F. Bonnan és Adam M. Yates (2007-ben) a Camelotiat, a Blikanasaurust és a Melanorosaurust feltételezett sauropodaként sorolta be.[36] Yates (2007-ben) bazális sauropodának nyilvánította az Antetonitrust, a Melanorosaurust és a Blikanasaurust, és elvetette a Prosauropoda alrendág használatát, mivel úgy vélte, hogy a Plateosauridae család szinonimájának tekinthető, habár nem zárta ki annak lehetőségét sem, hogy néhány prosauropoda, például a Plateosaurus, a Riojasaurus, a Massospondylus, valamint legközelebbi rokonaik monofiletikus csoportot alkothattak.[32]

A Massospondylus a Massospondylidae család típusneme és névadója. A Massospondylidae családba tartozik a Yunnanosaurus is,[37] habár Lu Junchang és más kutatók (2007-ben) a Yunnanosaurust saját családba sorolták be.[38] Yates (2007-ben) úgy vélte, hogy a Massospondylus, a Coloradisaurus és a Lufengosaurus massospondylidák, az Anchisauria kládba tartozó Yunnanosaurusszal együtt.[32] Nathan D. Smith és Diego Pol (2007-ben) egy filogenetikai elemzést végeztek, mely alapján a Massospondylus, a Coloradisaurus, és a Lufengosaurus mellett egy új nemet, a Glacialisaurust is a Massospondylidae család tagjaként osztályozták.[39] Az Adeopapposaurus olyan fosszíliákon alapul, amelyeket eredetileg a Massospondylus dél-amerikai képviselőjének gondolták, de később egy másik massospondylida nembe sorolták be.[2`
})
gomb8.addEventListener("click", function(){
    bek1.textContent = `A kora jura korban az állat- és növényvilág világszerte hasonló volt. A tűlevelűek alkalmazkodtak a forró időjáráshoz, és gyakori növényekké váltak,[40] míg a dinoszaurusz populáció fő részét a prosauropodák és a bazális theropodák alkották.[41] Dél-Afrikára a kora jura idején a sivatagi éghajlat volt jellemző.[42] Az afrikai Massospondylus kortársai voltak a crocodylomorphák, a tritylodontidák, a Trithelodontidae családba tartozó therapsidák és a Morganucodon nembe tartozó emlősök,[8] a dinoszauruszok között pedig az olyan kis theropodák, mint a Megapnosaurus rhodesiensis, a Melanorosaurus nem (M. thabanensis), a madármedencéjűek több korai képviselője, például a Lesothosaurus, a heterodontosauridák családjába tartozó Abrictosaurus, a Heterodontosaurus és a Lycorhinus.[31] Nem tisztázott, hogy a húsevők vadásztak-e a Massospondylusra.

A dél-afrikai kora jura kori rétegekből előkerült theropodák, például a Megapnosaurus, kisebbek voltak a Massospondylushoz hasonló közepes méretű prosauropodáknál. A kis ragadozóknak gyorsan és meglepetésszerűen kellett lecsapniuk a prosauropodákra, melyek a mellső és hátsó lábaikon levő karmaikkal védhették magukat.[42] A 6 méter hosszúságú[43] húsevő theropoda, a Dracovenator is ekkor élt (a hettangi és sinemuri korszakok során), és a maradványait megtalálták az Elliot-formációban is, ahonnan a Massospondylus előkerült.[44]

Ősbiológia
`
})
gomb9.addEventListener("click", function(){
    bek1.textContent = `Egy 2005-ös vizsgálat szerint a Massospondylus testvértaxonja, a Plateosaurus olyan növekedési mintákat mutat, amire hatással voltak a környezeti tényezők. Amikor bőségesen állt rendelkezésre az élelem, vagy amikor a klíma kedvezőbb volt, a Plateosaurus növekedése meggyorsult. Ez az úgynevezett „fejlődési képlékenység” más dinoszauruszoknál például a Massospondylusnál nem figyelhető meg, annak ellenére, hogy közeli rokonságban álltak egymással. A vizsgálat során az is kiderült, hogy a Massospondylus növekedése egy jellegzetes görbét követett, amely a növekedési arány változásokat és az egyedek végleges méretét illetően kis eltéréseket mutat.[45] Egy másik, kormeghatározással kapcsolatos vizsgálat szerint a Massospondylus átlagos növekedési aránya 17 kilogramm volt évente, és nagyjából 15 éves korára érte el a végleges méretét.[49]`
})
gomb10.addEventListener("click", function(){
    bek1.textContent = `A Massospondylus és más prosauropodák növényevők vagy mindenevők lehettek. Az 1980-as években és a 2000-es évek első felében az őslénykutatók arról vitatkoztak, hogy a prosauropodák képesek voltak-e húsevőként élni.[18][25] A húsevő prosauropodák elméletét azonban kétségbe vonták, és az újabb vizsgálatok már növényevő vagy mindenevő életmódot valószínűsítenek. Galton és Upchurch (2004-ben) úgy vélték, hogy a koponya jellegzetességei (például az állkapocs ízület) közelebb állnak a növényevő hüllőkéhez, mint a húsevőkéhez, míg a fogak koronájának alakja a modern növényevő vagy mindenevő leguángyíkokéra hasonlít. A fogkorona maximális szélessége nagyobb, mint a gyökéré, miáltal a vágóél a ma élő növényevő vagy mindenevő hüllőkére emlékeztet.[8] Paul M. Barrett (2000-ben) felvetette, hogy a prosauropodák kiegészíthették a növényi táplálékukat az általuk elejtett apróbb állatok vagy esetleg dögök húsának elfogyasztásával.[50] A zúzókövek (gasztrolitok), melyeket a dél-afrikai Massospondylus fosszíliákkal[13] és egy Virginia állambeli késő triász kori Massospondylusszerű állat maradványaival együtt találtak,[46] arról árulkodnak, hogy az állat köveket nyelt az emésztése megkönnyítésére;[13] az állat zúzájának izom-összehúzódásai porrá őrölték a lenyelt növényi anyagokat, kompenzálva a rágószervek tökéletlenségét.`
})
gomb11.addEventListener("click", function(){
    bek1.textContent = `1977-ben hét 190 millió éves tojást találtak a dél-afrikai Golden Gate Highlands National Parkban, melyeket James Kitching a Massospondylusénak tulajdonított. Közel 30 évvel később, a fosszíliákból 15 centiméter hosszú embriókat távolítottak el. Ezek a valaha talált legrégebbi dinoszaurusz embriók. A születendő utódoknak még nem voltak fogaik, ami alapján feltételezhető, hogy a születésük után nem tudták ellátni magukat. A lábaik közel egyenlő hosszúak voltak, így valószínű, hogy az újszülött Massospondylusok négy lábon jártak.[47] A koponya és a szemek a test arányait tekintve túlméretezettek voltak, ahogyan az más gerincesek fiatal példányainál is megfigyelhető, emellett pedig a koponyájuk magasabb és sokkal keskenyebb is volt a felnőttekénél.[13] Az utódok négylábúságából kikövetkeztethető, hogy a későbbi sauropodák e fiatalkori jellegzetesség visszamaradása (az úgynevezett pedomorfózis) révén váltak felnőtt korukra négy lábon járó állatokká.[47]`
})
gomb12.addEventListener("click", function(){
    bek1.textContent = `Más dinoszauruszokhoz hasonlóan a Massospondylus biológiájának nagy része, beleértve viselkedését, színét és fiziológiáját is, ismeretlen. A legújabb vizsgálatok azonban lehetővé tették, hogy a kutatók elméleteket gyártsanak a növekedési mintákat,[45] a táplálkozást,[46] a testhelyzetet,[7] a szaporodást[47] és a légzőrendszert[48] illetően.

Egy 2007-es tanulmány alapján a Massospondylus képes lehetett rövid karjait a ragadozókkal vagy a fajtársakkal való harc, valamint táplálkozás közben használni, bár a száját nem volt képes elérni velük. A tudósok úgy vélik, hogy a Massospondylus a nagy hüvelykujj karmai segítségével letéphette a fákról az ehető részeket,[7] de harc, ásás vagy akár a tisztálkodás[13] során is a segítségére lehettek.`
})
gomb13.addEventListener("click", function(){
    bek1.textContent = `Számos hüllőmedencéjű dinoszaurusz rendelkezett levegőtartalmú üreges csigolyákkal és bordákkal (foramina pneumatica), melyek amellett, hogy csökkentették a csontok tömegét, talán egyszerű átáramoltató cirkulációs rendszerként is működtek, amihez hasonló a modern madaraknál is megtalálható. Egy ilyen rendszerben üregesek a nyakcsigolyák és a bordák a nyaki légzsáknál, a hátcsigolyák a tüdőnél, a deréktáji és keresztcsonti (csípő) csigolyák pedig a hasi légzsáknál. Ezek a szervek egy nagyon hatékony és összetett légzőrendszert alkotnak.[51] A prosauropodák a hüllőmedencéjűek egyetlen nagyobb csoportja, melynek nincs kiterjedt foramina pneumatica rendszere. A Plateosaurusnál és a Thecodontosaurusnál találhatók olyan nyomok, amelyek a pneumatikus bemélyedésekre hasonlítanak, de kisebbek azoknál. Egy 2007-es vizsgálat, a testvértaxonoknál (a sauropodáknál és a theropodáknál) talált bizonyítékok alapján megállapította, hogy az olyan prosauropodáknak, mint a Massospondylus, valószínűleg voltak nyaki és hasi légzsákjaik. Bár nem sikerült meghatározni, hogy mely prosauropodáknak volt madárszerű átáramoltató tüdejük, az mindenesetre biztos, hogy már rendelkeztek légzsákokkal.[48]`
})